SECRET_MANAGER_RIA_CRED: "ms-ecuagiros-anticorrupcion/dev/credenciales-ria"
SECRET_MANAGER_INTERMEX_CRED: "ms-ecuagiros-anticorrupcion/dev/credenciales-intermex"
SECRET_MANAGER_TRANSNETWORK_CRED: "ms-ecuagiros-anticorrupcion/dev/credenciales-transnetwork"
VPC_ID: "vpc-0f60f40a693468f01"
SUBNET_1a: "subnet-04fd3c111aa247dd3"
SUBNET_1b: "subnet-01c7d7e51bb9f0f99"
SUBNET_1c: "subnet-009c54d6003f54329"
SECURITY_GROUP_DEFAULT: "sg-04fbb37ddc4599cc7"
NOTIFICATION_TOPIC_ARN: "arn:aws:sns:us-east-1:027558206260:ms-giros-masivo-dev-Notifications"
OCP_REQUEST_ONLINE_ORDER_CORE: "https://girt-recepcion-giros-bb-dev-giros.apps.ocpbbdevqa.desabbol.fin.ec/api/v1/girt-recepcion-pagos/consultGire"
OCP_VALIDATE_STATUS_ONLINE_ORDER: "https://girt-recepcion-giros-bb-dev-giros.apps.ocpbbdevqa.desabbol.fin.ec/api/v1/girt-recepcion-pagos/validateStatusGire"
OCP_PAY_ONLINE_ORDER: "https://girt-recepcion-giros-bb-dev-giros.apps.ocpbbdevqa.desabbol.fin.ec/api/v1/girt-recepcion-pagos/payGire"
OCP_CANCEL_ONLINE_PAYMENT_ORDER: "https://girt-recepcion-giros-bb-dev-giros.apps.ocpbbdevqa.desabbol.fin.ec/api/v1/girt-recepcion-pagos/cancelPayment"
OCP_REVERT_ONLINE_PAYMENT_ORDER: "https://girt-recepcion-giros-bb-dev-giros.apps.ocpbbdevqa.desabbol.fin.ec/api/v1/girt-recepcion-pagos/revertPaymentGire"
OCP_VALIDATE_BRIDGER_POLICIES: "https://ffpwdkutg3.execute-api.us-east-1.amazonaws.com/pre/listas-negras"
OCP_REVERSE_PAYMENT_ERROR: "https://girt-recepcion-giros-bb-dev-giros.apps.ocpbbdevqa.desabbol.fin.ec/api/v1/girt-recepcion-pagos/revertRequestSsn"
OCP_CREATE_GIRE_PAYMENT: "https://girt-recepcion-giros-bb-dev-giros.apps.ocpbbdevqa.desabbol.fin.ec/api/v1/girt-recepcion-pagos/createGire"
EVENT_BUS_ARN: "arn:aws:events:us-east-1:027558206260:event-bus/ms-giros-anticorrupcion-dev-giros-event-bus" 
ACCOUNT_ID: "027558206260"
TIME_CACHE_RECORD: "15"
FIRST_LIST_BRIDGER: "20241227054802"
SECOND_LIST_BRIDGER: "20241227054802"
USUARIO_BRIDGER: "afgarcim"
EMAIL_BRIDGER: "afgarcim@bolivariano.com"
SNS_ARN: "arn:aws:sns:us-east-1:027558206260:ms-giros-masivo-dev-Notifications"
AUTHORIZATION_URL: "https://ms-giros-enlinea-dev.auth.us-east-1.amazoncognito.com/oauth2/token"
TABLE_ONLINE_PAYMENTS: "ms-giros-enlinea-dev-online-payments"
URL_API_PRUEBA: "https://02c8-190-154-173-170.ngrok-free.app/api/conciliacion/orderNo"
TIME_EXPIRATION_CACHE: "24"
TIME_REINTENTOS: "15"
NUM_REINTENTOS: "2"
SM_ARN: "arn:aws:ssm:us-east-1:538884319140:parameter/int-ms-giros-conciliacion/dev"